---
title: "Data Wrangling"
author: "Aushanae Haller"
date: '2022-02-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(psych)
library(readr)
```

```{r}
tele <- read.csv("TeleCom_Dyad_premeasures.csv")

#names(tele)
#glimpse(tele)
```

```{r}
partners <- tele %>%
  mutate(relation_qual_1 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_1)),
         relation_qual_2 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_2)),
         relation_qual_3 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_3)),
         relation_qual_4 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_4)),
         relation_qual_5 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_5)),
         relation_qual_6 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_6)),
         relation_qual_7 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_7)),
         relation_qual_8 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_8)),
         relation_qual_9 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_9)),
         relation_qual_10 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_10)),
         relation_qual_11 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_11)),
         relation_qual_12 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_12)),
         relation_qual_13 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_13)),
         relation_qual_14 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_14)),
         relation_qual_15 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_15)),
         relation_qual_16 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_16)),
         relation_qual_17 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_17)),
         relation_qual_18 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_18)),
         relation_qual_19 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_19)),
         relation_qual_20 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_20)),
         relation_qual_21 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_21)),
         relation_qual_22 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_22)),
         relation_qual_23 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_23)),
         relation_qual_24 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_24)),
         relation_qual_25 = as.numeric(gsub("[a-zA-Z]", "", relation_qual_25)),
         self.object_1 = as.numeric(gsub("[a-zA-Z]", "", self.object_1)),
         self.object_2 = as.numeric(gsub("[a-zA-Z]", "", self.object_2)),
         self.object_3 = as.numeric(gsub("[a-zA-Z]", "", self.object_3)),
         self.object_4 = as.numeric(gsub("[a-zA-Z]", "", self.object_4)),
         self.object_5 = as.numeric(gsub("[a-zA-Z]", "", self.object_5)),
         self.object_6 = as.numeric(gsub("[a-zA-Z]", "", self.object_6)),
         self.object_7 = as.numeric(gsub("[a-zA-Z]", "", self.object_7)),
         self.object_8 = as.numeric(gsub("[a-zA-Z]", "", self.object_8)),
         self.object_9 = as.numeric(gsub("[a-zA-Z]", "", self.object_9)),
         self.object_10 = as.numeric(gsub("[a-zA-Z]", "", self.object_10)),
         other.object_1 = as.numeric(gsub("[a-zA-Z]", "", other.object_1)),
         other.object_2 = as.numeric(gsub("[a-zA-Z]", "", other.object_2)),
         other.object_3 = as.numeric(gsub("[a-zA-Z]", "", other.object_3)),
         other.object_4 = as.numeric(gsub("[a-zA-Z]", "", other.object_4)),
         other.object_5 = as.numeric(gsub("[a-zA-Z]", "", other.object_5)),
         other.object_6 = as.numeric(gsub("[a-zA-Z]", "", other.object_6)),
         other.object_7 = as.numeric(gsub("[a-zA-Z]", "", other.object_7)),
         other.object_8 = as.numeric(gsub("[a-zA-Z]", "", other.object_8)),
         other.object_9 = as.numeric(gsub("[a-zA-Z]", "", other.object_9)),
         other.object_10 = as.numeric(gsub("[a-zA-Z]", "", other.object_10))

  )

# Changing relationship qual 27 to numeric 

partners <- partners %>%
  mutate(relation_qual_27 =
           case_when(
             relation_qual_27 == "not too happy" ~ 1,
             relation_qual_27 == "pretty happy" ~ 2,
             relation_qual_27 == "very happy" ~ 3
           )
  )

```

```{r}
partners <- partners %>%
  select(relation_qual_1, relation_qual_2, relation_qual_3, relation_qual_4, relation_qual_5, relation_qual_6, relation_qual_7, relation_qual_8, relation_qual_9, relation_qual_10, relation_qual_11, relation_qual_12, relation_qual_13, relation_qual_14, relation_qual_15, relation_qual_16, relation_qual_17, relation_qual_18, relation_qual_19, relation_qual_20, relation_qual_21, relation_qual_22, relation_qual_23, relation_qual_24, relation_qual_25, relation_qual_26, relation_qual_27, self.object_1, self.object_2, self.object_3, self.object_4, self.object_5, self.object_6, self.object_7, self.object_8, self.object_9, self.object_10, other.object_1, other.object_2, other.object_3, other.object_4, other.object_5, other.object_6, other.object_7, other.object_8, other.object_9, other.object_10)

```

```{r}
# Filter out NAs and 999

partners <- partners %>% 
  # Relationship Quality missings
  filter(!is.na(relation_qual_1),
         !is.na(relation_qual_2),
         !is.na(relation_qual_3),
         !is.na(relation_qual_4),
         !is.na(relation_qual_5),
         !is.na(relation_qual_6),
         !is.na(relation_qual_7),
         !is.na(relation_qual_8),
         !is.na(relation_qual_9),
         !is.na(relation_qual_10),
         !is.na(relation_qual_11),
         !is.na(relation_qual_12),
         !is.na(relation_qual_13),
         !is.na(relation_qual_14),
         !is.na(relation_qual_15),
         !is.na(relation_qual_16),
         !is.na(relation_qual_17),
         !is.na(relation_qual_18),
         !is.na(relation_qual_19),
         !is.na(relation_qual_20),
         !is.na(relation_qual_21),
         !is.na(relation_qual_22),
         !is.na(relation_qual_23),
         !is.na(relation_qual_24),
         !is.na(relation_qual_25)) %>% 
  # Self Object missings
  filter(!is.na(self.object_1),
         !is.na(self.object_2),
         !is.na(self.object_3),
         !is.na(self.object_4),
         !is.na(self.object_5),
         !is.na(self.object_6),
         !is.na(self.object_7),
         !is.na(self.object_8),
         !is.na(self.object_9),
         !is.na(self.object_10)) %>% 
  # Other Object missings
  filter(!is.na(other.object_1),
         !is.na(other.object_2),
         !is.na(other.object_3),
         !is.na(other.object_4),
         !is.na(other.object_5),
         !is.na(other.object_6),
         !is.na(other.object_7),
         !is.na(other.object_8),
         !is.na(other.object_9),
         !is.na(self.object_10))
partners
```


# Create correlation matrix

```{r}

corr.test(select(partners, relation_qual_1:relation_qual_25))$r

corr.test(select(partners, other.object_1:other.object_10))$r

```

# Reverse score anything

```{r}
#Relationship Quality 1 - 12 Reverse Scoring

partners <- partners %>%
mutate(relation_qual_1 = (1 + 9) - relation_qual_1,
       relation_qual_2 = (1 + 9) - relation_qual_2,
       relation_qual_3 = (1 + 9) - relation_qual_3,
       relation_qual_4 = (1 + 9) - relation_qual_4,
       relation_qual_5 = (1 + 9) - relation_qual_5,
       relation_qual_6 = (1 + 9) - relation_qual_6,
       relation_qual_7 = (1 + 9) - relation_qual_7,
       relation_qual_8 = (1 + 9) - relation_qual_8,
       relation_qual_9 = (1 + 9) - relation_qual_9,
       relation_qual_10 = (1 + 9) - relation_qual_10
       )
```


# Calcutate chronbach's alpha

```{r}
partners$self_object <- rowMeans(select(partners, self.object_1, self.object_2, self.object_3, self.object_4, self.object_5, self.object_6, self.object_7, self.object_8, self.object_9, self.object_10))
partners$other_object <- rowMeans(select(partners, other.object_1, other.object_2, other.object_3, other.object_4, other.object_5, other.object_6, other.object_7, other.object_8, other.object_9, other.object_10))
partners <- partners %>%
  mutate(tso_mean = -1*(self_object - other_object))
partners <- partners %>%
  select(-c(self.object_1, self.object_2, self.object_3, self.object_4, self.object_5, self.object_6, self.object_7, self.object_8, self.object_9, self.object_10, other.object_1, other.object_2, other.object_3, other.object_4, other.object_5, other.object_6, other.object_7, other.object_8, other.object_9, other.object_10 ))
#names(Premeasures)
```

The gatekeeping in childcare scale was reliable, $\alpha$ = `r round(alpha_child, 2)`.

# Calculate Scale scores

```{r}
tele <- tele %>%
  mutate(gate_home = rowMeans(select(tele, gatekeeping_2, gatekeeping_3, gatekeeping_5, 
                 gatekeeping_7, gatekeeping_9, gatekeeping_11, 
                 gatekeeping_13, gatekeeping_16), na.rm = TRUE),
         gate_child = rowMeans(select(tele, gatekeeping_1, gatekeeping_4, gatekeeping_6, 
                 gatekeeping_8, gatekeeping_10, gatekeeping_12, 
                 gatekeeping_14, gatekeeping_15), na.rm = TRUE))

```
