---
title: "DS Tables & Figures"
author: "Aushanae Haller"
date: '2022-03-23'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(arsenal)
library(Hmisc)
library(data.table)
```


```{r}
# Demographics Table

demographics <- demographics_df %>%
  select(-dyadID) %>% 
  mutate(gender =
           case_when(gender == "Man" | gender == "Man,Cis gendered" ~ "Man",
                     gender == "Woman" | gender == "Woman,Cis gendered" ~ "Woman")
  )

my_labels <- list(
  race = "Race",
  birthday = "Age",
  sexualor = "Seuxal Orientation"
)

table_one <- tableby(gender ~ ., data = demographics, test = FALSE) 
summary(table_one, labelTranslations = my_labels, title = "Demographic Data") 
```


```{r}
# Correlations between Study Variables

vars <- pairwise %>% 
  select(relation_sat_A, self_object_A, other_object_A) %>% 
  rename("Relationship Quality" = relation_sat_A,
         "Self Objectification" = self_object_A,
         "Other Objectification" = other_object_A)

cor_table <- round(cor(vars, use="complete.obs"), 2)

cor_table[upper.tri(cor_table)]<-""

correlation <- as.data.frame(cor_table) %>% 
  mutate(M = 0, SD = 0)

correlation$M[1] <- mean(vars$`Relationship Quality`, na.rm = TRUE)
correlation$M[2] <- mean(vars$`Self Objectification`, na.rm = TRUE)
correlation$M[3] <- mean(vars$`Other Objectification`, na.rm = TRUE)
correlation$SD[1] <- sd(vars$`Relationship Quality`, na.rm = TRUE)
correlation$SD[2] <- sd(vars$`Self Objectification`, na.rm = TRUE)
correlation$SD[3] <- sd(vars$`Other Objectification`, na.rm = TRUE)

correlation <- correlation[, c(4, 5, 1, 2, 3)]

correlation
```

```{r, include=FALSE}
library(sjPlot)

pairwise_Nice <- pairwise %>%
  rename(Relationship_Satisfaction_Actor = relation_sat_A,
         Gender = gender_AF,
         Self_Objectification_Actor = self_object_A, 
         Other_Objectification_Actor = other_object_A,
         Self_Objectification_Partner = self_object_P, 
         Other_Objectification_Partner = other_object_P,)

apim_stp1 <- gls(Relationship_Satisfaction_Actor ~ Gender + 
                   Other_Objectification_Actor:Gender + 
                   Other_Objectification_Partner:Gender - 1,
                 data = pairwise_Nice,
                 correlation = corCompSymm(form=~1|Dyad_ID), 
                 weights = varIdent(form=~1|gender_A), 
                 na.action = na.omit)

apim_stp2 <- gls(Self_Objectification_Actor ~ Gender + 
                   Other_Objectification_Actor:Gender + 
                   Other_Objectification_Partner:Gender - 1,
                 data = pairwise_Nice,
                 correlation = corCompSymm(form=~1|Dyad_ID), 
                 weights = varIdent(form=~1|gender_A), 
                 na.action = na.omit)

pairwise_Nicer <- pairwise_Nice %>%
  rename(Relationship_Satisfaction_Actor_Controlling_for_Self_Objectification = Relationship_Satisfaction_Actor)

apim_stp3 <- gls(Relationship_Satisfaction_Actor_Controlling_for_Self_Objectification ~ Gender +
                   Other_Objectification_Actor:Gender + 
                   Other_Objectification_Partner:Gender + 
                   Self_Objectification_Actor:Gender + 
                   Self_Objectification_Partner:Gender - 1,
                 data = pairwise_Nicer,
                 correlation = corCompSymm(form=~1|Dyad_ID), 
                 weights = varIdent(form=~1|gender_A), 
                 na.action = na.omit)

```

```{r}
tab_model(apim_stp1, title = "Other Objectification vs. Relationship Satisfaction (Actor)")
```

```{r}
tab_model(apim_stp2)
```

```{r}
tab_model(apim_stp3)
```

```{r}
#all models together

tab_model(apim_stp1, apim_stp2, apim_stp3, title = "Other Objectification vs. Relationship Satisfaction Mediated by Self Objectification ")
```

